### add collection
POST http://localhost:8080//api/Collection
Content-Type: application/json

{
    "name": "collection2",
    "description": "description3",
    "creation_date": "2025-08-10",
    "modification_date": "2025-10-10",
    "still_updated": 1
}

### overwiew
GET http://localhost:8080/api/Overview

### list
GET http://localhost:8080/api/List

### info
GET http://localhost:8080/api/Info?name=collection

### add Backup
POST http://localhost:8080/api/Backup
Content-Type: application/json
{
    "name": "collection",
    "backup_name": "backup1",
    "date": "2025-10-10",
    "location": "BTH"
}
### Edit
POST http://localhost:8080/api/Edit
content-type: application/json

### Search specifik term
GET http://localhost:8080/api/Search?name=collection

### Search allt
GET http://localhost:8080/api/Search?name=

### Unbackup - Remove a backup from a collection
POST http://localhost:8080/api/Unbackup
Content-Type: application/json
{
  "name": "Customer Data",
  "backupname": "USB Drive Backup",
  "date": "2024-01-15"
}

