version: '3.8'

services:
  backup-organiser:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./static:/app/static
    environment:
      - FLASK_ENV=development
    command: python src/main.py